// SPDX-License-Identifier: Apache-2.0
// Embeds the seed directory (bots.json, skills/*.md, workflows/*.json,
// mcp.json) into apps/api/src/generated/seed.ts as a path -> content map,
// so single-file binaries (bun --compile) ship with working seed data and
// need no SEED_DIR on disk. The API extracts them to a temp dir at boot
// when SEED_DIR does not exist.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SEED_DIR = join(ROOT, 'seed');
const GEN_DIR = join(ROOT, 'apps/api/src/generated');
const GEN_FILE = join(GEN_DIR, 'seed.ts');

const header =
  `// SPDX-License-Identifier: Apache-2.0\n` +
  `// GENERATED by scripts/embed-seed.mjs — do not edit by hand.\n`;

mkdirSync(GEN_DIR, { recursive: true });

function walk(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p).forEach((f) => out.push(f));
    else out.push(p);
  }
  return out;
}

const files = walk(SEED_DIR);
const seedFiles = {};
for (const f of files) {
  const key = relative(SEED_DIR, f).split('\\').join('/');
  seedFiles[key] = readFileSync(f, 'utf8');
}

writeFileSync(
  GEN_FILE,
  header +
    `// ${files.length} seed files embedded from seed/.\n` +
    `export const SEED_FILES: Record<string, string> = ${JSON.stringify(seedFiles)};\n`,
);
console.log(`embedded ${files.length} seed files -> ${GEN_FILE}`);
