// SPDX-License-Identifier: Apache-2.0
// Embeds the Next.js static export (apps/web/out) into apps/api/src/generated/web-assets.ts
// as gzipped base64, so `bun build --compile` produces a SINGLE binary serving API + UI.
// In dev (file absent) the API falls back to express.static('../web/out').
import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const ROOT = dirname(fileURLToPath(new URL('.', import.meta.url)));
const OUT_DIR = join(ROOT, 'apps/web/out');
const GEN_DIR = join(ROOT, 'apps/api/src/generated');
const GEN_FILE = join(GEN_DIR, 'web-assets.ts');

const header =
  `// SPDX-License-Identifier: Apache-2.0\n` +
  `// GENERATED by scripts/embed-web.mjs — do not edit by hand.\n`;

mkdirSync(GEN_DIR, { recursive: true });

if (!existsSync(OUT_DIR)) {
  console.warn(`[embed-web] ${OUT_DIR} missing — writing empty asset map (run the web build first)`);
  writeFileSync(
    GEN_FILE,
    header +
      `export interface WebAsset { contentType: string; gzipBase64: string; }\n` +
      `export const WEB_ASSETS: Record<string, WebAsset> = {};\n`,
  );
  process.exit(0);
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
};

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p).forEach((f) => out.push(f));
    else out.push(p);
  }
  return out;
}

const files = walk(OUT_DIR);
const assets = {};
for (const f of files) {
  const key = '/' + relative(OUT_DIR, f).split('\\').join('/');
  const buf = readFileSync(f);
  assets[key] = {
    contentType: MIME[extname(f).toLowerCase()] || 'application/octet-stream',
    gzipBase64: gzipSync(buf).toString('base64'),
  };
}

writeFileSync(
  GEN_FILE,
  header +
    `// ${files.length} files embedded from apps/web/out.\n` +
    `export interface WebAsset { contentType: string; gzipBase64: string; }\n` +
    `export const WEB_ASSETS: Record<string, WebAsset> = ${JSON.stringify(assets)};\n`
);
console.log(`embedded ${files.length} files -> ${GEN_FILE}`);
